-- DML to insert 44 new questions with MFCC references
-- Note: 6 words were skipped due to missing source audio: father, gloves, goat, ice cream, shirt, shoes

INSERT INTO questions (teks, level) VALUES 
('Cup', 'Kids'),
('Plate', 'Kids'),
('Spoon', 'Kids'),
('Fork', 'Kids'),
('Bag', 'Kids'),
('Pants', 'Kids'),
('Hat', 'Kids'),
('Chicken', 'Kids'),
('Horse', 'Kids'),
('Duck', 'Kids'),
('Frog', 'Kids'),
('Bed', 'Kids'),
('Door', 'Kids'),
('Window', 'Kids'),
('Lamp', 'Kids'),
('Clock', 'Kids'),
('Candy', 'Kids'),
('Chocolate', 'Kids'),
('Cookie', 'Kids'),
('Honey', 'Kids'),
('Brother', 'Kids'),
('Sister', 'Kids'),
('Mother', 'Kids'),
('Baby', 'Kids'),
('Run', 'Kids'),
('Jump', 'Kids'),
('Sleep', 'Kids'),
('Eat', 'Kids'),
('Drink', 'Kids'),
('Smile', 'Kids'),
('Cry', 'Kids'),
('Sing', 'Kids'),
('Dance', 'Kids'),
('Play', 'Kids'),
('Beach', 'Kids'),
('Mountain', 'Kids'),
('River', 'Kids'),
('Forest', 'Kids'),
('Park', 'Kids'),
('Cupcake', 'Kids'),
('Pencil', 'Kids'),
('Crayon', 'Kids'),
('Notebook', 'Kids'),
('Backpack', 'Kids');
